/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'entityId' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'actorPrincipal' : Principal,
  'entityType' : string,
  'farmId' : bigint,
}
export interface ClassificationCode {
  'taxSection' : string,
  'code' : string,
  'incomeType' : string,
  'guidance' : string,
}
export interface ClassificationEntry {
  'code' : string,
  'description' : string,
  'warnings' : Array<string>,
  'examples' : Array<string>,
}
export interface CropHarvest {
  'id' : bigint,
  'moisturePercent' : [] | [number],
  'actualYieldQt' : number,
  'recordedBy' : Principal,
  'notes' : [] | [string],
  'qualityGrade' : QualityGrade,
  'cropSeasonId' : bigint,
  'harvestDate' : Timestamp,
}
export interface CropMSP {
  'id' : bigint,
  'financialYear' : string,
  'mspPerQuintal' : bigint,
  'lastUpdated' : Timestamp,
  'season' : string,
  'cropName' : string,
}
export interface CropSeason {
  'id' : bigint,
  'isInterCrop' : boolean,
  'financialYear' : string,
  'actualYieldQt' : [] | [number],
  'mspPerQuintal' : [] | [bigint],
  'expectedHarvestDate' : Timestamp,
  'createdAt' : Timestamp,
  'season' : string,
  'stage' : CropStage,
  'parentCropId' : [] | [bigint],
  'cropName' : string,
  'areaSqm' : bigint,
  'variety' : string,
  'expectedYieldQt' : [] | [number],
  'farmId' : bigint,
  'sowingDate' : Timestamp,
  'fieldId' : bigint,
}
export type CropStage = { 'Germination' : null } |
  { 'GrainFilling' : null } |
  { 'Sowing' : null } |
  { 'Harvest' : null } |
  { 'LandPrep' : null } |
  { 'PostHarvest' : null } |
  { 'Vegetative' : null } |
  { 'Flowering' : null };
export interface Farm {
  'id' : bigint,
  'ownershipType' : string,
  'ownerPrincipal' : Principal,
  'ksId' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'surveyNumber' : [] | [string],
  'isDemo' : boolean,
  'purposes' : Array<string>,
  'totalAreaSqm' : bigint,
  'district' : string,
  'state' : string,
  'village' : string,
  'mandal' : string,
}
export interface FarmMember {
  'id' : bigint,
  'principal' : [] | [Principal],
  'relation' : string,
  'lastActiveAt' : [] | [Timestamp],
  'name' : string,
  'joinedAt' : Timestamp,
  'role' : MemberRole,
  'emoji' : string,
  'addedBy' : Principal,
  'moduleToggles' : ModuleToggles,
  'phone' : [] | [string],
  'farmId' : bigint,
}
export interface FarmerProfile {
  'fssaiNumber' : [] | [string],
  'principal' : Principal,
  'bankLast4' : [] | [string],
  'gstNumber' : [] | [string],
  'name' : string,
  'fpoMember' : boolean,
  'bankIfsc' : [] | [string],
  'aadhaarBankLinked' : boolean,
  'mobile' : [] | [string],
  'agristackId' : [] | [string],
  'bankBranch' : [] | [string],
}
export interface Field {
  'id' : bigint,
  'shcExpiry' : [] | [Timestamp],
  'soilType' : string,
  'irrigationType' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'landRecordRef' : [] | [string],
  'surveyNumber' : [] | [string],
  'isActive' : boolean,
  'geoPoints' : Array<[number, number]>,
  'ulpin' : [] | [string],
  'areaSqm' : bigint,
  'tenure' : string,
  'shcNumber' : [] | [string],
  'farmId' : bigint,
}
export interface InviteToken {
  'id' : bigint,
  'token' : string,
  'expiresAt' : Timestamp,
  'code' : string,
  'hmac' : string,
  'createdBy' : Principal,
  'role' : MemberRole,
  'moduleToggles' : ModuleToggles,
  'acceptedBy' : [] | [Principal],
  'revokedAt' : [] | [Timestamp],
  'farmId' : bigint,
}
export interface LandRecord {
  'id' : bigint,
  'pahaniNumber' : [] | [string],
  'satbaraNumber' : [] | [string],
  'bhudhaarNumber' : [] | [string],
  'adangalNumber' : [] | [string],
  'state' : string,
  'pattadarPassbook' : [] | [string],
  'genericRecordNumber' : [] | [string],
  'rtcNumber' : [] | [string],
  'fieldId' : bigint,
}
export type MemberRole = { 'Member' : null } |
  { 'ViewOnly' : null } |
  { 'Admin' : null };
export interface ModuleToggles {
  'finance' : boolean,
  'fisheries' : boolean,
  'poultry' : boolean,
  'labour' : boolean,
  'crops' : boolean,
  'greenhouse' : boolean,
  'solar' : boolean,
  'horticulture' : boolean,
  'dairy' : boolean,
  'machinery' : boolean,
}
export interface NotificationEntity {
  'id' : bigint,
  'title' : string,
  'notifType' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'soundType' : string,
  'isRead' : boolean,
  'snoozedUntil' : [] | [Timestamp],
  'isDismissed' : boolean,
  'recipientPrincipal' : Principal,
  'farmId' : bigint,
}
export type QualityGrade = { 'FAQ' : null } |
  { 'GradeA' : null } |
  { 'GradeB' : null } |
  { 'Rejected' : null } |
  { 'Processing' : null };
export type Result = { 'ok' : FarmMember } |
  { 'err' : string };
export type Result_1 = { 'ok' : Field } |
  { 'err' : string };
export type Result_10 = { 'ok' : Array<Field> } |
  { 'err' : string };
export type Result_11 = { 'ok' : Array<FarmMember> } |
  { 'err' : string };
export type Result_12 = { 'ok' : Array<CropSeason> } |
  { 'err' : string };
export type Result_13 = { 'ok' : [] | [CropMSP] } |
  { 'err' : string };
export type Result_14 = { 'ok' : Array<AuditLog> } |
  { 'err' : string };
export type Result_15 = { 'ok' : Array<InviteToken> } |
  { 'err' : string };
export type Result_16 = { 'ok' : InviteToken } |
  { 'err' : string };
export type Result_17 = { 'ok' : ClassificationCode } |
  { 'err' : string };
export type Result_2 = { 'ok' : Farm } |
  { 'err' : string };
export type Result_3 = { 'ok' : CropSeason } |
  { 'err' : string };
export type Result_4 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_5 = { 'ok' : LandRecord } |
  { 'err' : string };
export type Result_6 = { 'ok' : FarmerProfile } |
  { 'err' : string };
export type Result_7 = { 'ok' : CropHarvest } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<NotificationEntity> } |
  { 'err' : string };
export type Result_9 = { 'ok' : [] | [LandRecord] } |
  { 'err' : string };
export interface SaveLandRecordInput {
  'pahaniNumber' : [] | [string],
  'satbaraNumber' : [] | [string],
  'bhudhaarNumber' : [] | [string],
  'adangalNumber' : [] | [string],
  'state' : string,
  'pattadarPassbook' : [] | [string],
  'genericRecordNumber' : [] | [string],
  'rtcNumber' : [] | [string],
}
export type Timestamp = bigint;
export interface UpdateFarmInput {
  'ownershipType' : [] | [string],
  'name' : [] | [string],
  'surveyNumber' : [] | [string],
  'purposes' : [] | [Array<string>],
  'totalAreaSqm' : [] | [bigint],
  'district' : [] | [string],
  'village' : [] | [string],
  'mandal' : [] | [string],
}
export interface UpdateFieldInput {
  'shcExpiry' : [] | [Timestamp],
  'soilType' : [] | [string],
  'irrigationType' : [] | [string],
  'name' : [] | [string],
  'unit' : [] | [string],
  'surveyNumber' : [] | [string],
  'geoPoints' : [] | [Array<[number, number]>],
  'ulpin' : [] | [string],
  'areaSqm' : [] | [bigint],
  'tenure' : [] | [string],
  'shcNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptInvite' : ActorMethod<[string], Result_2>,
  'addFarmMember' : ActorMethod<
    [bigint, string, string, string, [] | [string], MemberRole, ModuleToggles],
    Result
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'classifyIncome' : ActorMethod<[string, string, string], Result_17>,
  'createCropSeason' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      Timestamp,
      Timestamp,
      [] | [bigint],
      boolean,
      [] | [bigint],
    ],
    Result_3
  >,
  'createFarm' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      bigint,
      string,
      string,
      Array<string>,
    ],
    Result_2
  >,
  'createField' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [Timestamp],
      Array<[number, number]>,
    ],
    Result_1
  >,
  'deleteField' : ActorMethod<[bigint], Result_4>,
  'generateInvite' : ActorMethod<
    [bigint, MemberRole, ModuleToggles],
    Result_16
  >,
  'getActiveInvites' : ActorMethod<[bigint], Result_15>,
  'getAllMSPRates' : ActorMethod<[string], Array<CropMSP>>,
  'getAuditLog' : ActorMethod<[bigint, bigint], Result_14>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassificationCodes' : ActorMethod<[], Array<ClassificationEntry>>,
  'getCropMSP' : ActorMethod<[string, string, string], Result_13>,
  'getCropSeasonsForFarm' : ActorMethod<[bigint, string], Result_12>,
  'getCropSeasonsForField' : ActorMethod<[bigint], Result_12>,
  'getDemoFarm' : ActorMethod<[], Result_2>,
  'getFarm' : ActorMethod<[bigint], Result_2>,
  'getFarmMembers' : ActorMethod<[bigint], Result_11>,
  'getFarmerProfile' : ActorMethod<[], Result_6>,
  'getFieldsForFarm' : ActorMethod<[bigint], Result_10>,
  'getLandRecord' : ActorMethod<[bigint], Result_9>,
  'getNotifications' : ActorMethod<[bigint], Result_8>,
  'getUserFarms' : ActorMethod<[], Array<Farm>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logHarvest' : ActorMethod<
    [bigint, Timestamp, number, QualityGrade, [] | [number], [] | [string]],
    Result_7
  >,
  'markNotificationRead' : ActorMethod<[bigint], Result_4>,
  'removeFarmMember' : ActorMethod<[bigint, bigint], Result_4>,
  'revokeInvite' : ActorMethod<[bigint, bigint], Result_4>,
  'saveFarmerProfile' : ActorMethod<[FarmerProfile], Result_6>,
  'saveLandRecord' : ActorMethod<[bigint, SaveLandRecordInput], Result_5>,
  'snoozeNotification' : ActorMethod<[bigint, Timestamp], Result_4>,
  'updateCropStage' : ActorMethod<[bigint, CropStage], Result_3>,
  'updateFarm' : ActorMethod<[bigint, UpdateFarmInput], Result_2>,
  'updateField' : ActorMethod<[bigint, UpdateFieldInput], Result_1>,
  'updateMemberRole' : ActorMethod<[bigint, bigint, MemberRole], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];