/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Farm = IDL.Record({
  'id' : IDL.Nat,
  'ownershipType' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'ksId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'surveyNumber' : IDL.Opt(IDL.Text),
  'isDemo' : IDL.Bool,
  'purposes' : IDL.Vec(IDL.Text),
  'totalAreaSqm' : IDL.Nat,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'village' : IDL.Text,
  'mandal' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : Farm, 'err' : IDL.Text });
export const MemberRole = IDL.Variant({
  'Member' : IDL.Null,
  'ViewOnly' : IDL.Null,
  'Admin' : IDL.Null,
});
export const ModuleToggles = IDL.Record({
  'finance' : IDL.Bool,
  'fisheries' : IDL.Bool,
  'poultry' : IDL.Bool,
  'labour' : IDL.Bool,
  'crops' : IDL.Bool,
  'greenhouse' : IDL.Bool,
  'solar' : IDL.Bool,
  'horticulture' : IDL.Bool,
  'dairy' : IDL.Bool,
  'machinery' : IDL.Bool,
});
export const FarmMember = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Opt(IDL.Principal),
  'relation' : IDL.Text,
  'lastActiveAt' : IDL.Opt(Timestamp),
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'role' : MemberRole,
  'emoji' : IDL.Text,
  'addedBy' : IDL.Principal,
  'moduleToggles' : ModuleToggles,
  'phone' : IDL.Opt(IDL.Text),
  'farmId' : IDL.Nat,
});
export const Result = IDL.Variant({ 'ok' : FarmMember, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClassificationCode = IDL.Record({
  'taxSection' : IDL.Text,
  'code' : IDL.Text,
  'incomeType' : IDL.Text,
  'guidance' : IDL.Text,
});
export const Result_17 = IDL.Variant({
  'ok' : ClassificationCode,
  'err' : IDL.Text,
});
export const CropStage = IDL.Variant({
  'Germination' : IDL.Null,
  'GrainFilling' : IDL.Null,
  'Sowing' : IDL.Null,
  'Harvest' : IDL.Null,
  'LandPrep' : IDL.Null,
  'PostHarvest' : IDL.Null,
  'Vegetative' : IDL.Null,
  'Flowering' : IDL.Null,
});
export const CropSeason = IDL.Record({
  'id' : IDL.Nat,
  'isInterCrop' : IDL.Bool,
  'financialYear' : IDL.Text,
  'actualYieldQt' : IDL.Opt(IDL.Float64),
  'mspPerQuintal' : IDL.Opt(IDL.Nat),
  'expectedHarvestDate' : Timestamp,
  'createdAt' : Timestamp,
  'season' : IDL.Text,
  'stage' : CropStage,
  'parentCropId' : IDL.Opt(IDL.Nat),
  'cropName' : IDL.Text,
  'areaSqm' : IDL.Nat,
  'variety' : IDL.Text,
  'expectedYieldQt' : IDL.Opt(IDL.Float64),
  'farmId' : IDL.Nat,
  'sowingDate' : Timestamp,
  'fieldId' : IDL.Nat,
});
export const Result_3 = IDL.Variant({ 'ok' : CropSeason, 'err' : IDL.Text });
export const Field = IDL.Record({
  'id' : IDL.Nat,
  'shcExpiry' : IDL.Opt(Timestamp),
  'soilType' : IDL.Text,
  'irrigationType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'landRecordRef' : IDL.Opt(IDL.Text),
  'surveyNumber' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'geoPoints' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
  'ulpin' : IDL.Opt(IDL.Text),
  'areaSqm' : IDL.Nat,
  'tenure' : IDL.Text,
  'shcNumber' : IDL.Opt(IDL.Text),
  'farmId' : IDL.Nat,
});
export const Result_1 = IDL.Variant({ 'ok' : Field, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const InviteToken = IDL.Record({
  'id' : IDL.Nat,
  'token' : IDL.Text,
  'expiresAt' : Timestamp,
  'code' : IDL.Text,
  'hmac' : IDL.Text,
  'createdBy' : IDL.Principal,
  'role' : MemberRole,
  'moduleToggles' : ModuleToggles,
  'acceptedBy' : IDL.Opt(IDL.Principal),
  'revokedAt' : IDL.Opt(Timestamp),
  'farmId' : IDL.Nat,
});
export const Result_16 = IDL.Variant({ 'ok' : InviteToken, 'err' : IDL.Text });
export const Result_15 = IDL.Variant({
  'ok' : IDL.Vec(InviteToken),
  'err' : IDL.Text,
});
export const CropMSP = IDL.Record({
  'id' : IDL.Nat,
  'financialYear' : IDL.Text,
  'mspPerQuintal' : IDL.Nat,
  'lastUpdated' : Timestamp,
  'season' : IDL.Text,
  'cropName' : IDL.Text,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'entityId' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
  'entityType' : IDL.Text,
  'farmId' : IDL.Nat,
});
export const Result_14 = IDL.Variant({
  'ok' : IDL.Vec(AuditLog),
  'err' : IDL.Text,
});
export const ClassificationEntry = IDL.Record({
  'code' : IDL.Text,
  'description' : IDL.Text,
  'warnings' : IDL.Vec(IDL.Text),
  'examples' : IDL.Vec(IDL.Text),
});
export const Result_13 = IDL.Variant({
  'ok' : IDL.Opt(CropMSP),
  'err' : IDL.Text,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Vec(CropSeason),
  'err' : IDL.Text,
});
export const Result_11 = IDL.Variant({
  'ok' : IDL.Vec(FarmMember),
  'err' : IDL.Text,
});
export const FarmerProfile = IDL.Record({
  'fssaiNumber' : IDL.Opt(IDL.Text),
  'principal' : IDL.Principal,
  'bankLast4' : IDL.Opt(IDL.Text),
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'fpoMember' : IDL.Bool,
  'bankIfsc' : IDL.Opt(IDL.Text),
  'aadhaarBankLinked' : IDL.Bool,
  'mobile' : IDL.Opt(IDL.Text),
  'agristackId' : IDL.Opt(IDL.Text),
  'bankBranch' : IDL.Opt(IDL.Text),
});
export const Result_6 = IDL.Variant({ 'ok' : FarmerProfile, 'err' : IDL.Text });
export const Result_10 = IDL.Variant({
  'ok' : IDL.Vec(Field),
  'err' : IDL.Text,
});
export const LandRecord = IDL.Record({
  'id' : IDL.Nat,
  'pahaniNumber' : IDL.Opt(IDL.Text),
  'satbaraNumber' : IDL.Opt(IDL.Text),
  'bhudhaarNumber' : IDL.Opt(IDL.Text),
  'adangalNumber' : IDL.Opt(IDL.Text),
  'state' : IDL.Text,
  'pattadarPassbook' : IDL.Opt(IDL.Text),
  'genericRecordNumber' : IDL.Opt(IDL.Text),
  'rtcNumber' : IDL.Opt(IDL.Text),
  'fieldId' : IDL.Nat,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Opt(LandRecord),
  'err' : IDL.Text,
});
export const NotificationEntity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'notifType' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'soundType' : IDL.Text,
  'isRead' : IDL.Bool,
  'snoozedUntil' : IDL.Opt(Timestamp),
  'isDismissed' : IDL.Bool,
  'recipientPrincipal' : IDL.Principal,
  'farmId' : IDL.Nat,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(NotificationEntity),
  'err' : IDL.Text,
});
export const QualityGrade = IDL.Variant({
  'FAQ' : IDL.Null,
  'GradeA' : IDL.Null,
  'GradeB' : IDL.Null,
  'Rejected' : IDL.Null,
  'Processing' : IDL.Null,
});
export const CropHarvest = IDL.Record({
  'id' : IDL.Nat,
  'moisturePercent' : IDL.Opt(IDL.Float64),
  'actualYieldQt' : IDL.Float64,
  'recordedBy' : IDL.Principal,
  'notes' : IDL.Opt(IDL.Text),
  'qualityGrade' : QualityGrade,
  'cropSeasonId' : IDL.Nat,
  'harvestDate' : Timestamp,
});
export const Result_7 = IDL.Variant({ 'ok' : CropHarvest, 'err' : IDL.Text });
export const SaveLandRecordInput = IDL.Record({
  'pahaniNumber' : IDL.Opt(IDL.Text),
  'satbaraNumber' : IDL.Opt(IDL.Text),
  'bhudhaarNumber' : IDL.Opt(IDL.Text),
  'adangalNumber' : IDL.Opt(IDL.Text),
  'state' : IDL.Text,
  'pattadarPassbook' : IDL.Opt(IDL.Text),
  'genericRecordNumber' : IDL.Opt(IDL.Text),
  'rtcNumber' : IDL.Opt(IDL.Text),
});
export const Result_5 = IDL.Variant({ 'ok' : LandRecord, 'err' : IDL.Text });
export const UpdateFarmInput = IDL.Record({
  'ownershipType' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'surveyNumber' : IDL.Opt(IDL.Text),
  'purposes' : IDL.Opt(IDL.Vec(IDL.Text)),
  'totalAreaSqm' : IDL.Opt(IDL.Nat),
  'district' : IDL.Opt(IDL.Text),
  'village' : IDL.Opt(IDL.Text),
  'mandal' : IDL.Opt(IDL.Text),
});
export const UpdateFieldInput = IDL.Record({
  'shcExpiry' : IDL.Opt(Timestamp),
  'soilType' : IDL.Opt(IDL.Text),
  'irrigationType' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'unit' : IDL.Opt(IDL.Text),
  'surveyNumber' : IDL.Opt(IDL.Text),
  'geoPoints' : IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64))),
  'ulpin' : IDL.Opt(IDL.Text),
  'areaSqm' : IDL.Opt(IDL.Nat),
  'tenure' : IDL.Opt(IDL.Text),
  'shcNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptInvite' : IDL.Func([IDL.Text], [Result_2], []),
  'addFarmMember' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        MemberRole,
        ModuleToggles,
      ],
      [Result],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'classifyIncome' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_17],
      ['query'],
    ),
  'createCropSeason' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Timestamp,
        Timestamp,
        IDL.Opt(IDL.Nat),
        IDL.Bool,
        IDL.Opt(IDL.Nat),
      ],
      [Result_3],
      [],
    ),
  'createFarm' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [Result_2],
      [],
    ),
  'createField' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Timestamp),
        IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
      ],
      [Result_1],
      [],
    ),
  'deleteField' : IDL.Func([IDL.Nat], [Result_4], []),
  'generateInvite' : IDL.Func(
      [IDL.Nat, MemberRole, ModuleToggles],
      [Result_16],
      [],
    ),
  'getActiveInvites' : IDL.Func([IDL.Nat], [Result_15], ['query']),
  'getAllMSPRates' : IDL.Func([IDL.Text], [IDL.Vec(CropMSP)], ['query']),
  'getAuditLog' : IDL.Func([IDL.Nat, IDL.Nat], [Result_14], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassificationCodes' : IDL.Func(
      [],
      [IDL.Vec(ClassificationEntry)],
      ['query'],
    ),
  'getCropMSP' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_13],
      ['query'],
    ),
  'getCropSeasonsForFarm' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [Result_12],
      ['query'],
    ),
  'getCropSeasonsForField' : IDL.Func([IDL.Nat], [Result_12], ['query']),
  'getDemoFarm' : IDL.Func([], [Result_2], ['query']),
  'getFarm' : IDL.Func([IDL.Nat], [Result_2], ['query']),
  'getFarmMembers' : IDL.Func([IDL.Nat], [Result_11], ['query']),
  'getFarmerProfile' : IDL.Func([], [Result_6], ['query']),
  'getFieldsForFarm' : IDL.Func([IDL.Nat], [Result_10], ['query']),
  'getLandRecord' : IDL.Func([IDL.Nat], [Result_9], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [Result_8], ['query']),
  'getUserFarms' : IDL.Func([], [IDL.Vec(Farm)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logHarvest' : IDL.Func(
      [
        IDL.Nat,
        Timestamp,
        IDL.Float64,
        QualityGrade,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [Result_7],
      [],
    ),
  'markNotificationRead' : IDL.Func([IDL.Nat], [Result_4], []),
  'removeFarmMember' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], []),
  'revokeInvite' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], []),
  'saveFarmerProfile' : IDL.Func([FarmerProfile], [Result_6], []),
  'saveLandRecord' : IDL.Func([IDL.Nat, SaveLandRecordInput], [Result_5], []),
  'snoozeNotification' : IDL.Func([IDL.Nat, Timestamp], [Result_4], []),
  'updateCropStage' : IDL.Func([IDL.Nat, CropStage], [Result_3], []),
  'updateFarm' : IDL.Func([IDL.Nat, UpdateFarmInput], [Result_2], []),
  'updateField' : IDL.Func([IDL.Nat, UpdateFieldInput], [Result_1], []),
  'updateMemberRole' : IDL.Func([IDL.Nat, IDL.Nat, MemberRole], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Farm = IDL.Record({
    'id' : IDL.Nat,
    'ownershipType' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'ksId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'surveyNumber' : IDL.Opt(IDL.Text),
    'isDemo' : IDL.Bool,
    'purposes' : IDL.Vec(IDL.Text),
    'totalAreaSqm' : IDL.Nat,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'village' : IDL.Text,
    'mandal' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : Farm, 'err' : IDL.Text });
  const MemberRole = IDL.Variant({
    'Member' : IDL.Null,
    'ViewOnly' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const ModuleToggles = IDL.Record({
    'finance' : IDL.Bool,
    'fisheries' : IDL.Bool,
    'poultry' : IDL.Bool,
    'labour' : IDL.Bool,
    'crops' : IDL.Bool,
    'greenhouse' : IDL.Bool,
    'solar' : IDL.Bool,
    'horticulture' : IDL.Bool,
    'dairy' : IDL.Bool,
    'machinery' : IDL.Bool,
  });
  const FarmMember = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Opt(IDL.Principal),
    'relation' : IDL.Text,
    'lastActiveAt' : IDL.Opt(Timestamp),
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'role' : MemberRole,
    'emoji' : IDL.Text,
    'addedBy' : IDL.Principal,
    'moduleToggles' : ModuleToggles,
    'phone' : IDL.Opt(IDL.Text),
    'farmId' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : FarmMember, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClassificationCode = IDL.Record({
    'taxSection' : IDL.Text,
    'code' : IDL.Text,
    'incomeType' : IDL.Text,
    'guidance' : IDL.Text,
  });
  const Result_17 = IDL.Variant({
    'ok' : ClassificationCode,
    'err' : IDL.Text,
  });
  const CropStage = IDL.Variant({
    'Germination' : IDL.Null,
    'GrainFilling' : IDL.Null,
    'Sowing' : IDL.Null,
    'Harvest' : IDL.Null,
    'LandPrep' : IDL.Null,
    'PostHarvest' : IDL.Null,
    'Vegetative' : IDL.Null,
    'Flowering' : IDL.Null,
  });
  const CropSeason = IDL.Record({
    'id' : IDL.Nat,
    'isInterCrop' : IDL.Bool,
    'financialYear' : IDL.Text,
    'actualYieldQt' : IDL.Opt(IDL.Float64),
    'mspPerQuintal' : IDL.Opt(IDL.Nat),
    'expectedHarvestDate' : Timestamp,
    'createdAt' : Timestamp,
    'season' : IDL.Text,
    'stage' : CropStage,
    'parentCropId' : IDL.Opt(IDL.Nat),
    'cropName' : IDL.Text,
    'areaSqm' : IDL.Nat,
    'variety' : IDL.Text,
    'expectedYieldQt' : IDL.Opt(IDL.Float64),
    'farmId' : IDL.Nat,
    'sowingDate' : Timestamp,
    'fieldId' : IDL.Nat,
  });
  const Result_3 = IDL.Variant({ 'ok' : CropSeason, 'err' : IDL.Text });
  const Field = IDL.Record({
    'id' : IDL.Nat,
    'shcExpiry' : IDL.Opt(Timestamp),
    'soilType' : IDL.Text,
    'irrigationType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'landRecordRef' : IDL.Opt(IDL.Text),
    'surveyNumber' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'geoPoints' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
    'ulpin' : IDL.Opt(IDL.Text),
    'areaSqm' : IDL.Nat,
    'tenure' : IDL.Text,
    'shcNumber' : IDL.Opt(IDL.Text),
    'farmId' : IDL.Nat,
  });
  const Result_1 = IDL.Variant({ 'ok' : Field, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const InviteToken = IDL.Record({
    'id' : IDL.Nat,
    'token' : IDL.Text,
    'expiresAt' : Timestamp,
    'code' : IDL.Text,
    'hmac' : IDL.Text,
    'createdBy' : IDL.Principal,
    'role' : MemberRole,
    'moduleToggles' : ModuleToggles,
    'acceptedBy' : IDL.Opt(IDL.Principal),
    'revokedAt' : IDL.Opt(Timestamp),
    'farmId' : IDL.Nat,
  });
  const Result_16 = IDL.Variant({ 'ok' : InviteToken, 'err' : IDL.Text });
  const Result_15 = IDL.Variant({
    'ok' : IDL.Vec(InviteToken),
    'err' : IDL.Text,
  });
  const CropMSP = IDL.Record({
    'id' : IDL.Nat,
    'financialYear' : IDL.Text,
    'mspPerQuintal' : IDL.Nat,
    'lastUpdated' : Timestamp,
    'season' : IDL.Text,
    'cropName' : IDL.Text,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'entityId' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
    'entityType' : IDL.Text,
    'farmId' : IDL.Nat,
  });
  const Result_14 = IDL.Variant({ 'ok' : IDL.Vec(AuditLog), 'err' : IDL.Text });
  const ClassificationEntry = IDL.Record({
    'code' : IDL.Text,
    'description' : IDL.Text,
    'warnings' : IDL.Vec(IDL.Text),
    'examples' : IDL.Vec(IDL.Text),
  });
  const Result_13 = IDL.Variant({ 'ok' : IDL.Opt(CropMSP), 'err' : IDL.Text });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Vec(CropSeason),
    'err' : IDL.Text,
  });
  const Result_11 = IDL.Variant({
    'ok' : IDL.Vec(FarmMember),
    'err' : IDL.Text,
  });
  const FarmerProfile = IDL.Record({
    'fssaiNumber' : IDL.Opt(IDL.Text),
    'principal' : IDL.Principal,
    'bankLast4' : IDL.Opt(IDL.Text),
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'fpoMember' : IDL.Bool,
    'bankIfsc' : IDL.Opt(IDL.Text),
    'aadhaarBankLinked' : IDL.Bool,
    'mobile' : IDL.Opt(IDL.Text),
    'agristackId' : IDL.Opt(IDL.Text),
    'bankBranch' : IDL.Opt(IDL.Text),
  });
  const Result_6 = IDL.Variant({ 'ok' : FarmerProfile, 'err' : IDL.Text });
  const Result_10 = IDL.Variant({ 'ok' : IDL.Vec(Field), 'err' : IDL.Text });
  const LandRecord = IDL.Record({
    'id' : IDL.Nat,
    'pahaniNumber' : IDL.Opt(IDL.Text),
    'satbaraNumber' : IDL.Opt(IDL.Text),
    'bhudhaarNumber' : IDL.Opt(IDL.Text),
    'adangalNumber' : IDL.Opt(IDL.Text),
    'state' : IDL.Text,
    'pattadarPassbook' : IDL.Opt(IDL.Text),
    'genericRecordNumber' : IDL.Opt(IDL.Text),
    'rtcNumber' : IDL.Opt(IDL.Text),
    'fieldId' : IDL.Nat,
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Opt(LandRecord),
    'err' : IDL.Text,
  });
  const NotificationEntity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'notifType' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'soundType' : IDL.Text,
    'isRead' : IDL.Bool,
    'snoozedUntil' : IDL.Opt(Timestamp),
    'isDismissed' : IDL.Bool,
    'recipientPrincipal' : IDL.Principal,
    'farmId' : IDL.Nat,
  });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Vec(NotificationEntity),
    'err' : IDL.Text,
  });
  const QualityGrade = IDL.Variant({
    'FAQ' : IDL.Null,
    'GradeA' : IDL.Null,
    'GradeB' : IDL.Null,
    'Rejected' : IDL.Null,
    'Processing' : IDL.Null,
  });
  const CropHarvest = IDL.Record({
    'id' : IDL.Nat,
    'moisturePercent' : IDL.Opt(IDL.Float64),
    'actualYieldQt' : IDL.Float64,
    'recordedBy' : IDL.Principal,
    'notes' : IDL.Opt(IDL.Text),
    'qualityGrade' : QualityGrade,
    'cropSeasonId' : IDL.Nat,
    'harvestDate' : Timestamp,
  });
  const Result_7 = IDL.Variant({ 'ok' : CropHarvest, 'err' : IDL.Text });
  const SaveLandRecordInput = IDL.Record({
    'pahaniNumber' : IDL.Opt(IDL.Text),
    'satbaraNumber' : IDL.Opt(IDL.Text),
    'bhudhaarNumber' : IDL.Opt(IDL.Text),
    'adangalNumber' : IDL.Opt(IDL.Text),
    'state' : IDL.Text,
    'pattadarPassbook' : IDL.Opt(IDL.Text),
    'genericRecordNumber' : IDL.Opt(IDL.Text),
    'rtcNumber' : IDL.Opt(IDL.Text),
  });
  const Result_5 = IDL.Variant({ 'ok' : LandRecord, 'err' : IDL.Text });
  const UpdateFarmInput = IDL.Record({
    'ownershipType' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'surveyNumber' : IDL.Opt(IDL.Text),
    'purposes' : IDL.Opt(IDL.Vec(IDL.Text)),
    'totalAreaSqm' : IDL.Opt(IDL.Nat),
    'district' : IDL.Opt(IDL.Text),
    'village' : IDL.Opt(IDL.Text),
    'mandal' : IDL.Opt(IDL.Text),
  });
  const UpdateFieldInput = IDL.Record({
    'shcExpiry' : IDL.Opt(Timestamp),
    'soilType' : IDL.Opt(IDL.Text),
    'irrigationType' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'unit' : IDL.Opt(IDL.Text),
    'surveyNumber' : IDL.Opt(IDL.Text),
    'geoPoints' : IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64))),
    'ulpin' : IDL.Opt(IDL.Text),
    'areaSqm' : IDL.Opt(IDL.Nat),
    'tenure' : IDL.Opt(IDL.Text),
    'shcNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptInvite' : IDL.Func([IDL.Text], [Result_2], []),
    'addFarmMember' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          MemberRole,
          ModuleToggles,
        ],
        [Result],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'classifyIncome' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_17],
        ['query'],
      ),
    'createCropSeason' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Timestamp,
          Timestamp,
          IDL.Opt(IDL.Nat),
          IDL.Bool,
          IDL.Opt(IDL.Nat),
        ],
        [Result_3],
        [],
      ),
    'createFarm' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [Result_2],
        [],
      ),
    'createField' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Timestamp),
          IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
        ],
        [Result_1],
        [],
      ),
    'deleteField' : IDL.Func([IDL.Nat], [Result_4], []),
    'generateInvite' : IDL.Func(
        [IDL.Nat, MemberRole, ModuleToggles],
        [Result_16],
        [],
      ),
    'getActiveInvites' : IDL.Func([IDL.Nat], [Result_15], ['query']),
    'getAllMSPRates' : IDL.Func([IDL.Text], [IDL.Vec(CropMSP)], ['query']),
    'getAuditLog' : IDL.Func([IDL.Nat, IDL.Nat], [Result_14], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassificationCodes' : IDL.Func(
        [],
        [IDL.Vec(ClassificationEntry)],
        ['query'],
      ),
    'getCropMSP' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_13],
        ['query'],
      ),
    'getCropSeasonsForFarm' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [Result_12],
        ['query'],
      ),
    'getCropSeasonsForField' : IDL.Func([IDL.Nat], [Result_12], ['query']),
    'getDemoFarm' : IDL.Func([], [Result_2], ['query']),
    'getFarm' : IDL.Func([IDL.Nat], [Result_2], ['query']),
    'getFarmMembers' : IDL.Func([IDL.Nat], [Result_11], ['query']),
    'getFarmerProfile' : IDL.Func([], [Result_6], ['query']),
    'getFieldsForFarm' : IDL.Func([IDL.Nat], [Result_10], ['query']),
    'getLandRecord' : IDL.Func([IDL.Nat], [Result_9], ['query']),
    'getNotifications' : IDL.Func([IDL.Nat], [Result_8], ['query']),
    'getUserFarms' : IDL.Func([], [IDL.Vec(Farm)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logHarvest' : IDL.Func(
        [
          IDL.Nat,
          Timestamp,
          IDL.Float64,
          QualityGrade,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [Result_7],
        [],
      ),
    'markNotificationRead' : IDL.Func([IDL.Nat], [Result_4], []),
    'removeFarmMember' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], []),
    'revokeInvite' : IDL.Func([IDL.Nat, IDL.Nat], [Result_4], []),
    'saveFarmerProfile' : IDL.Func([FarmerProfile], [Result_6], []),
    'saveLandRecord' : IDL.Func([IDL.Nat, SaveLandRecordInput], [Result_5], []),
    'snoozeNotification' : IDL.Func([IDL.Nat, Timestamp], [Result_4], []),
    'updateCropStage' : IDL.Func([IDL.Nat, CropStage], [Result_3], []),
    'updateFarm' : IDL.Func([IDL.Nat, UpdateFarmInput], [Result_2], []),
    'updateField' : IDL.Func([IDL.Nat, UpdateFieldInput], [Result_1], []),
    'updateMemberRole' : IDL.Func([IDL.Nat, IDL.Nat, MemberRole], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };