/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Field {
    id: bigint;
    shcExpiry?: Timestamp;
    soilType: string;
    irrigationType: string;
    name: string;
    createdAt: Timestamp;
    unit: string;
    landRecordRef?: string;
    surveyNumber?: string;
    isActive: boolean;
    geoPoints: Array<[number, number]>;
    ulpin?: string;
    areaSqm: bigint;
    tenure: string;
    shcNumber?: string;
    farmId: bigint;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Farm;
} | {
    __kind__: "err";
    err: string;
};
export type Result_17 = {
    __kind__: "ok";
    ok: ClassificationCode;
} | {
    __kind__: "err";
    err: string;
};
export type Result_13 = {
    __kind__: "ok";
    ok: CropMSP | null;
} | {
    __kind__: "err";
    err: string;
};
export interface AuditLog {
    id: bigint;
    action: string;
    entityId: string;
    timestamp: Timestamp;
    details: string;
    actorPrincipal: Principal;
    entityType: string;
    farmId: bigint;
}
export type Result_5 = {
    __kind__: "ok";
    ok: LandRecord;
} | {
    __kind__: "err";
    err: string;
};
export type Result_16 = {
    __kind__: "ok";
    ok: InviteToken;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Field;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type Result_11 = {
    __kind__: "ok";
    ok: Array<FarmMember>;
} | {
    __kind__: "err";
    err: string;
};
export interface CropSeason {
    id: bigint;
    isInterCrop: boolean;
    financialYear: string;
    actualYieldQt?: number;
    mspPerQuintal?: bigint;
    expectedHarvestDate: Timestamp;
    createdAt: Timestamp;
    season: string;
    stage: CropStage;
    parentCropId?: bigint;
    cropName: string;
    areaSqm: bigint;
    variety: string;
    expectedYieldQt?: number;
    farmId: bigint;
    sowingDate: Timestamp;
    fieldId: bigint;
}
export interface InviteToken {
    id: bigint;
    token: string;
    expiresAt: Timestamp;
    code: string;
    hmac: string;
    createdBy: Principal;
    role: MemberRole;
    moduleToggles: ModuleToggles;
    acceptedBy?: Principal;
    revokedAt?: Timestamp;
    farmId: bigint;
}
export interface ModuleToggles {
    finance: boolean;
    fisheries: boolean;
    poultry: boolean;
    labour: boolean;
    crops: boolean;
    greenhouse: boolean;
    solar: boolean;
    horticulture: boolean;
    dairy: boolean;
    machinery: boolean;
}
export interface ClassificationEntry {
    code: string;
    description: string;
    warnings: Array<string>;
    examples: Array<string>;
}
export type Result_7 = {
    __kind__: "ok";
    ok: CropHarvest;
} | {
    __kind__: "err";
    err: string;
};
export type Result_14 = {
    __kind__: "ok";
    ok: Array<AuditLog>;
} | {
    __kind__: "err";
    err: string;
};
export interface FarmMember {
    id: bigint;
    principal?: Principal;
    relation: string;
    lastActiveAt?: Timestamp;
    name: string;
    joinedAt: Timestamp;
    role: MemberRole;
    emoji: string;
    addedBy: Principal;
    moduleToggles: ModuleToggles;
    phone?: string;
    farmId: bigint;
}
export interface Farm {
    id: bigint;
    ownershipType: string;
    ownerPrincipal: Principal;
    ksId: string;
    name: string;
    createdAt: Timestamp;
    surveyNumber?: string;
    isDemo: boolean;
    purposes: Array<string>;
    totalAreaSqm: bigint;
    district: string;
    state: string;
    village: string;
    mandal: string;
}
export interface SaveLandRecordInput {
    pahaniNumber?: string;
    satbaraNumber?: string;
    bhudhaarNumber?: string;
    adangalNumber?: string;
    state: string;
    pattadarPassbook?: string;
    genericRecordNumber?: string;
    rtcNumber?: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: FarmerProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface CropMSP {
    id: bigint;
    financialYear: string;
    mspPerQuintal: bigint;
    lastUpdated: Timestamp;
    season: string;
    cropName: string;
}
export interface UpdateFarmInput {
    ownershipType?: string;
    name?: string;
    surveyNumber?: string;
    purposes?: Array<string>;
    totalAreaSqm?: bigint;
    district?: string;
    village?: string;
    mandal?: string;
}
export type Result_9 = {
    __kind__: "ok";
    ok: LandRecord | null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_12 = {
    __kind__: "ok";
    ok: Array<CropSeason>;
} | {
    __kind__: "err";
    err: string;
};
export interface CropHarvest {
    id: bigint;
    moisturePercent?: number;
    actualYieldQt: number;
    recordedBy: Principal;
    notes?: string;
    qualityGrade: QualityGrade;
    cropSeasonId: bigint;
    harvestDate: Timestamp;
}
export interface ClassificationCode {
    taxSection: string;
    code: string;
    incomeType: string;
    guidance: string;
}
export interface NotificationEntity {
    id: bigint;
    title: string;
    notifType: string;
    body: string;
    createdAt: Timestamp;
    soundType: string;
    isRead: boolean;
    snoozedUntil?: Timestamp;
    isDismissed: boolean;
    recipientPrincipal: Principal;
    farmId: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: FarmMember;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: CropSeason;
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateFieldInput {
    shcExpiry?: Timestamp;
    soilType?: string;
    irrigationType?: string;
    name?: string;
    unit?: string;
    surveyNumber?: string;
    geoPoints?: Array<[number, number]>;
    ulpin?: string;
    areaSqm?: bigint;
    tenure?: string;
    shcNumber?: string;
}
export type Result_10 = {
    __kind__: "ok";
    ok: Array<Field>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: Array<NotificationEntity>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_15 = {
    __kind__: "ok";
    ok: Array<InviteToken>;
} | {
    __kind__: "err";
    err: string;
};
export interface FarmerProfile {
    fssaiNumber?: string;
    principal: Principal;
    bankLast4?: string;
    gstNumber?: string;
    name: string;
    fpoMember: boolean;
    bankIfsc?: string;
    aadhaarBankLinked: boolean;
    mobile?: string;
    agristackId?: string;
    bankBranch?: string;
}
export interface LandRecord {
    id: bigint;
    pahaniNumber?: string;
    satbaraNumber?: string;
    bhudhaarNumber?: string;
    adangalNumber?: string;
    state: string;
    pattadarPassbook?: string;
    genericRecordNumber?: string;
    rtcNumber?: string;
    fieldId: bigint;
}
export enum CropStage {
    Germination = "Germination",
    GrainFilling = "GrainFilling",
    Sowing = "Sowing",
    Harvest = "Harvest",
    LandPrep = "LandPrep",
    PostHarvest = "PostHarvest",
    Vegetative = "Vegetative",
    Flowering = "Flowering"
}
export enum MemberRole {
    Member = "Member",
    ViewOnly = "ViewOnly",
    Admin = "Admin"
}
export enum QualityGrade {
    FAQ = "FAQ",
    GradeA = "GradeA",
    GradeB = "GradeB",
    Rejected = "Rejected",
    Processing = "Processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    acceptInvite(code: string): Promise<Result_2>;
    addFarmMember(farmId: bigint, name: string, relation: string, emoji: string, phone: string | null, role: MemberRole, moduleToggles: ModuleToggles): Promise<Result>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    classifyIncome(module: string, itemType: string, marketChannel: string): Promise<Result_17>;
    createCropSeason(farmId: bigint, fieldId: bigint, cropName: string, variety: string, season: string, financialYear: string, areaSqm: bigint, sowingDate: Timestamp, expectedHarvestDate: Timestamp, mspPerQuintal: bigint | null, isInterCrop: boolean, parentCropId: bigint | null): Promise<Result_3>;
    createFarm(name: string, state: string, district: string, mandal: string, village: string, surveyNumber: string | null, totalAreaSqm: bigint, unit: string, ownershipType: string, purposes: Array<string>): Promise<Result_2>;
    createField(farmId: bigint, name: string, areaSqm: bigint, unit: string, soilType: string, irrigationType: string, tenure: string, surveyNumber: string | null, ulpin: string | null, shcNumber: string | null, shcExpiry: Timestamp | null, geoPoints: Array<[number, number]>): Promise<Result_1>;
    deleteField(fieldId: bigint): Promise<Result_4>;
    generateInvite(farmId: bigint, role: MemberRole, moduleToggles: ModuleToggles): Promise<Result_16>;
    getActiveInvites(farmId: bigint): Promise<Result_15>;
    getAllMSPRates(financialYear: string): Promise<Array<CropMSP>>;
    getAuditLog(farmId: bigint, limit: bigint): Promise<Result_14>;
    getCallerUserRole(): Promise<UserRole>;
    getClassificationCodes(): Promise<Array<ClassificationEntry>>;
    getCropMSP(cropName: string, season: string, financialYear: string): Promise<Result_13>;
    getCropSeasonsForFarm(farmId: bigint, financialYear: string): Promise<Result_12>;
    getCropSeasonsForField(fieldId: bigint): Promise<Result_12>;
    getDemoFarm(): Promise<Result_2>;
    getFarm(farmId: bigint): Promise<Result_2>;
    getFarmMembers(farmId: bigint): Promise<Result_11>;
    getFarmerProfile(): Promise<Result_6>;
    getFieldsForFarm(farmId: bigint): Promise<Result_10>;
    getLandRecord(fieldId: bigint): Promise<Result_9>;
    getNotifications(farmId: bigint): Promise<Result_8>;
    getUserFarms(): Promise<Array<Farm>>;
    isCallerAdmin(): Promise<boolean>;
    logHarvest(cropSeasonId: bigint, harvestDate: Timestamp, yieldQt: number, qualityGrade: QualityGrade, moisturePercent: number | null, notes: string | null): Promise<Result_7>;
    markNotificationRead(notifId: bigint): Promise<Result_4>;
    removeFarmMember(farmId: bigint, memberId: bigint): Promise<Result_4>;
    revokeInvite(farmId: bigint, inviteId: bigint): Promise<Result_4>;
    saveFarmerProfile(profile: FarmerProfile): Promise<Result_6>;
    saveLandRecord(fieldId: bigint, record: SaveLandRecordInput): Promise<Result_5>;
    snoozeNotification(notifId: bigint, until: Timestamp): Promise<Result_4>;
    updateCropStage(cropSeasonId: bigint, stage: CropStage): Promise<Result_3>;
    updateFarm(farmId: bigint, updates: UpdateFarmInput): Promise<Result_2>;
    updateField(fieldId: bigint, updates: UpdateFieldInput): Promise<Result_1>;
    updateMemberRole(farmId: bigint, memberId: bigint, newRole: MemberRole): Promise<Result>;
}
import type { AuditLog as _AuditLog, ClassificationCode as _ClassificationCode, CropHarvest as _CropHarvest, CropMSP as _CropMSP, CropSeason as _CropSeason, CropStage as _CropStage, Farm as _Farm, FarmMember as _FarmMember, FarmerProfile as _FarmerProfile, Field as _Field, InviteToken as _InviteToken, LandRecord as _LandRecord, MemberRole as _MemberRole, ModuleToggles as _ModuleToggles, NotificationEntity as _NotificationEntity, QualityGrade as _QualityGrade, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_12 as _Result_12, Result_13 as _Result_13, Result_14 as _Result_14, Result_15 as _Result_15, Result_16 as _Result_16, Result_17 as _Result_17, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, SaveLandRecordInput as _SaveLandRecordInput, Timestamp as _Timestamp, UpdateFarmInput as _UpdateFarmInput, UpdateFieldInput as _UpdateFieldInput, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptInvite(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptInvite(arg0);
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptInvite(arg0);
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFarmMember(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: MemberRole, arg6: ModuleToggles): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addFarmMember(arg0, arg1, arg2, arg3, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), to_candid_MemberRole_n7(this._uploadFile, this._downloadFile, arg5), arg6);
                return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFarmMember(arg0, arg1, arg2, arg3, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), to_candid_MemberRole_n7(this._uploadFile, this._downloadFile, arg5), arg6);
            return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async classifyIncome(arg0: string, arg1: string, arg2: string): Promise<Result_17> {
        if (this.processError) {
            try {
                const result = await this.actor.classifyIncome(arg0, arg1, arg2);
                return from_candid_Result_17_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.classifyIncome(arg0, arg1, arg2);
            return from_candid_Result_17_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCropSeason(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: Timestamp, arg8: Timestamp, arg9: bigint | null, arg10: boolean, arg11: bigint | null): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createCropSeason(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg9), arg10, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg11));
                return from_candid_Result_3_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCropSeason(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg9), arg10, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg11));
            return from_candid_Result_3_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFarm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: bigint, arg7: string, arg8: string, arg9: Array<string>): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createFarm(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFarm(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createField(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string | null, arg8: string | null, arg9: string | null, arg10: Timestamp | null, arg11: Array<[number, number]>): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createField(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg10), arg11);
                return from_candid_Result_1_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createField(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg10), arg11);
            return from_candid_Result_1_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteField(arg0: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteField(arg0);
                return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteField(arg0);
            return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateInvite(arg0: bigint, arg1: MemberRole, arg2: ModuleToggles): Promise<Result_16> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInvite(arg0, to_candid_MemberRole_n7(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Result_16_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInvite(arg0, to_candid_MemberRole_n7(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Result_16_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveInvites(arg0: bigint): Promise<Result_15> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveInvites(arg0);
                return from_candid_Result_15_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveInvites(arg0);
            return from_candid_Result_15_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMSPRates(arg0: string): Promise<Array<CropMSP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMSPRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMSPRates(arg0);
            return result;
        }
    }
    async getAuditLog(arg0: bigint, arg1: bigint): Promise<Result_14> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(arg0, arg1);
                return from_candid_Result_14_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(arg0, arg1);
            return from_candid_Result_14_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassificationCodes(): Promise<Array<ClassificationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassificationCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassificationCodes();
            return result;
        }
    }
    async getCropMSP(arg0: string, arg1: string, arg2: string): Promise<Result_13> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropMSP(arg0, arg1, arg2);
                return from_candid_Result_13_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropMSP(arg0, arg1, arg2);
            return from_candid_Result_13_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropSeasonsForFarm(arg0: bigint, arg1: string): Promise<Result_12> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropSeasonsForFarm(arg0, arg1);
                return from_candid_Result_12_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropSeasonsForFarm(arg0, arg1);
            return from_candid_Result_12_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropSeasonsForField(arg0: bigint): Promise<Result_12> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropSeasonsForField(arg0);
                return from_candid_Result_12_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropSeasonsForField(arg0);
            return from_candid_Result_12_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDemoFarm(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemoFarm();
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemoFarm();
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarm(arg0: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarm(arg0);
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarm(arg0);
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmMembers(arg0: bigint): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmMembers(arg0);
                return from_candid_Result_11_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmMembers(arg0);
            return from_candid_Result_11_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmerProfile(): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerProfile();
                return from_candid_Result_6_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerProfile();
            return from_candid_Result_6_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFieldsForFarm(arg0: bigint): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.getFieldsForFarm(arg0);
                return from_candid_Result_10_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFieldsForFarm(arg0);
            return from_candid_Result_10_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLandRecord(arg0: bigint): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.getLandRecord(arg0);
                return from_candid_Result_9_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLandRecord(arg0);
            return from_candid_Result_9_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_Result_8_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_Result_8_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFarms(): Promise<Array<Farm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFarms();
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFarms();
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logHarvest(arg0: bigint, arg1: Timestamp, arg2: number, arg3: QualityGrade, arg4: number | null, arg5: string | null): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.logHarvest(arg0, arg1, arg2, to_candid_QualityGrade_n75(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n77(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Result_7_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logHarvest(arg0, arg1, arg2, to_candid_QualityGrade_n75(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n77(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Result_7_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFarmMember(arg0: bigint, arg1: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFarmMember(arg0, arg1);
                return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFarmMember(arg0, arg1);
            return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeInvite(arg0: bigint, arg1: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInvite(arg0, arg1);
                return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInvite(arg0, arg1);
            return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveFarmerProfile(arg0: FarmerProfile): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFarmerProfile(to_candid_FarmerProfile_n84(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_6_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFarmerProfile(to_candid_FarmerProfile_n84(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_6_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveLandRecord(arg0: bigint, arg1: SaveLandRecordInput): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLandRecord(arg0, to_candid_SaveLandRecordInput_n86(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_5_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLandRecord(arg0, to_candid_SaveLandRecordInput_n86(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_5_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async snoozeNotification(arg0: bigint, arg1: Timestamp): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.snoozeNotification(arg0, arg1);
                return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.snoozeNotification(arg0, arg1);
            return from_candid_Result_4_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCropStage(arg0: bigint, arg1: CropStage): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCropStage(arg0, to_candid_CropStage_n90(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_3_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCropStage(arg0, to_candid_CropStage_n90(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_3_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFarm(arg0: bigint, arg1: UpdateFarmInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFarm(arg0, to_candid_UpdateFarmInput_n92(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFarm(arg0, to_candid_UpdateFarmInput_n92(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateField(arg0: bigint, arg1: UpdateFieldInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateField(arg0, to_candid_UpdateFieldInput_n94(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateField(arg0, to_candid_UpdateFieldInput_n94(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMemberRole(arg0: bigint, arg1: bigint, arg2: MemberRole): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberRole(arg0, arg1, to_candid_MemberRole_n7(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberRole(arg0, arg1, to_candid_MemberRole_n7(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CropHarvest_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropHarvest): CropHarvest {
    return from_candid_record_n81(_uploadFile, _downloadFile, value);
}
function from_candid_CropSeason_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropSeason): CropSeason {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CropStage_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropStage): CropStage {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_FarmMember_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmMember): FarmMember {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Farm_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Farm): Farm {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FarmerProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmerProfile): FarmerProfile {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Field_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Field): Field {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_InviteToken_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteToken): InviteToken {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_LandRecord_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LandRecord): LandRecord {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_MemberRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberRole): MemberRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationEntity_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationEntity): NotificationEntity {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_QualityGrade_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QualityGrade): QualityGrade {
    return from_candid_variant_n83(_uploadFile, _downloadFile, value);
}
function from_candid_Result_10_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Result_11_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_11): Result_11 {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Result_12_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_12): Result_12 {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Result_13_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_13): Result_13 {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Result_14_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_14): Result_14 {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result_15_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_15): Result_15 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_16_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_16): Result_16 {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Result_17_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_17): Result_17 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n79(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CropMSP]): CropMSP | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LandRecord]): LandRecord | null {
    return value.length === 0 ? null : from_candid_LandRecord_n67(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: [] | [Principal];
    relation: string;
    lastActiveAt: [] | [_Timestamp];
    name: string;
    joinedAt: _Timestamp;
    role: _MemberRole;
    emoji: string;
    addedBy: Principal;
    moduleToggles: _ModuleToggles;
    phone: [] | [string];
    farmId: bigint;
}): {
    id: bigint;
    principal?: Principal;
    relation: string;
    lastActiveAt?: Timestamp;
    name: string;
    joinedAt: Timestamp;
    role: MemberRole;
    emoji: string;
    addedBy: Principal;
    moduleToggles: ModuleToggles;
    phone?: string;
    farmId: bigint;
} {
    return {
        id: value.id,
        principal: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.principal)),
        relation: value.relation,
        lastActiveAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastActiveAt)),
        name: value.name,
        joinedAt: value.joinedAt,
        role: from_candid_MemberRole_n15(_uploadFile, _downloadFile, value.role),
        emoji: value.emoji,
        addedBy: value.addedBy,
        moduleToggles: value.moduleToggles,
        phone: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.phone)),
        farmId: value.farmId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isInterCrop: boolean;
    financialYear: string;
    actualYieldQt: [] | [number];
    mspPerQuintal: [] | [bigint];
    expectedHarvestDate: _Timestamp;
    createdAt: _Timestamp;
    season: string;
    stage: _CropStage;
    parentCropId: [] | [bigint];
    cropName: string;
    areaSqm: bigint;
    variety: string;
    expectedYieldQt: [] | [number];
    farmId: bigint;
    sowingDate: _Timestamp;
    fieldId: bigint;
}): {
    id: bigint;
    isInterCrop: boolean;
    financialYear: string;
    actualYieldQt?: number;
    mspPerQuintal?: bigint;
    expectedHarvestDate: Timestamp;
    createdAt: Timestamp;
    season: string;
    stage: CropStage;
    parentCropId?: bigint;
    cropName: string;
    areaSqm: bigint;
    variety: string;
    expectedYieldQt?: number;
    farmId: bigint;
    sowingDate: Timestamp;
    fieldId: bigint;
} {
    return {
        id: value.id,
        isInterCrop: value.isInterCrop,
        financialYear: value.financialYear,
        actualYieldQt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.actualYieldQt)),
        mspPerQuintal: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.mspPerQuintal)),
        expectedHarvestDate: value.expectedHarvestDate,
        createdAt: value.createdAt,
        season: value.season,
        stage: from_candid_CropStage_n28(_uploadFile, _downloadFile, value.stage),
        parentCropId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.parentCropId)),
        cropName: value.cropName,
        areaSqm: value.areaSqm,
        variety: value.variety,
        expectedYieldQt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.expectedYieldQt)),
        farmId: value.farmId,
        sowingDate: value.sowingDate,
        fieldId: value.fieldId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    shcExpiry: [] | [_Timestamp];
    soilType: string;
    irrigationType: string;
    name: string;
    createdAt: _Timestamp;
    unit: string;
    landRecordRef: [] | [string];
    surveyNumber: [] | [string];
    isActive: boolean;
    geoPoints: Array<[number, number]>;
    ulpin: [] | [string];
    areaSqm: bigint;
    tenure: string;
    shcNumber: [] | [string];
    farmId: bigint;
}): {
    id: bigint;
    shcExpiry?: Timestamp;
    soilType: string;
    irrigationType: string;
    name: string;
    createdAt: Timestamp;
    unit: string;
    landRecordRef?: string;
    surveyNumber?: string;
    isActive: boolean;
    geoPoints: Array<[number, number]>;
    ulpin?: string;
    areaSqm: bigint;
    tenure: string;
    shcNumber?: string;
    farmId: bigint;
} {
    return {
        id: value.id,
        shcExpiry: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.shcExpiry)),
        soilType: value.soilType,
        irrigationType: value.irrigationType,
        name: value.name,
        createdAt: value.createdAt,
        unit: value.unit,
        landRecordRef: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.landRecordRef)),
        surveyNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.surveyNumber)),
        isActive: value.isActive,
        geoPoints: value.geoPoints,
        ulpin: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.ulpin)),
        areaSqm: value.areaSqm,
        tenure: value.tenure,
        shcNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.shcNumber)),
        farmId: value.farmId
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ownershipType: string;
    ownerPrincipal: Principal;
    ksId: string;
    name: string;
    createdAt: _Timestamp;
    surveyNumber: [] | [string];
    isDemo: boolean;
    purposes: Array<string>;
    totalAreaSqm: bigint;
    district: string;
    state: string;
    village: string;
    mandal: string;
}): {
    id: bigint;
    ownershipType: string;
    ownerPrincipal: Principal;
    ksId: string;
    name: string;
    createdAt: Timestamp;
    surveyNumber?: string;
    isDemo: boolean;
    purposes: Array<string>;
    totalAreaSqm: bigint;
    district: string;
    state: string;
    village: string;
    mandal: string;
} {
    return {
        id: value.id,
        ownershipType: value.ownershipType,
        ownerPrincipal: value.ownerPrincipal,
        ksId: value.ksId,
        name: value.name,
        createdAt: value.createdAt,
        surveyNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.surveyNumber)),
        isDemo: value.isDemo,
        purposes: value.purposes,
        totalAreaSqm: value.totalAreaSqm,
        district: value.district,
        state: value.state,
        village: value.village,
        mandal: value.mandal
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    token: string;
    expiresAt: _Timestamp;
    code: string;
    hmac: string;
    createdBy: Principal;
    role: _MemberRole;
    moduleToggles: _ModuleToggles;
    acceptedBy: [] | [Principal];
    revokedAt: [] | [_Timestamp];
    farmId: bigint;
}): {
    id: bigint;
    token: string;
    expiresAt: Timestamp;
    code: string;
    hmac: string;
    createdBy: Principal;
    role: MemberRole;
    moduleToggles: ModuleToggles;
    acceptedBy?: Principal;
    revokedAt?: Timestamp;
    farmId: bigint;
} {
    return {
        id: value.id,
        token: value.token,
        expiresAt: value.expiresAt,
        code: value.code,
        hmac: value.hmac,
        createdBy: value.createdBy,
        role: from_candid_MemberRole_n15(_uploadFile, _downloadFile, value.role),
        moduleToggles: value.moduleToggles,
        acceptedBy: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.acceptedBy)),
        revokedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.revokedAt)),
        farmId: value.farmId
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fssaiNumber: [] | [string];
    principal: Principal;
    bankLast4: [] | [string];
    gstNumber: [] | [string];
    name: string;
    fpoMember: boolean;
    bankIfsc: [] | [string];
    aadhaarBankLinked: boolean;
    mobile: [] | [string];
    agristackId: [] | [string];
    bankBranch: [] | [string];
}): {
    fssaiNumber?: string;
    principal: Principal;
    bankLast4?: string;
    gstNumber?: string;
    name: string;
    fpoMember: boolean;
    bankIfsc?: string;
    aadhaarBankLinked: boolean;
    mobile?: string;
    agristackId?: string;
    bankBranch?: string;
} {
    return {
        fssaiNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.fssaiNumber)),
        principal: value.principal,
        bankLast4: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bankLast4)),
        gstNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.gstNumber)),
        name: value.name,
        fpoMember: value.fpoMember,
        bankIfsc: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bankIfsc)),
        aadhaarBankLinked: value.aadhaarBankLinked,
        mobile: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.mobile)),
        agristackId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.agristackId)),
        bankBranch: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bankBranch))
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pahaniNumber: [] | [string];
    satbaraNumber: [] | [string];
    bhudhaarNumber: [] | [string];
    adangalNumber: [] | [string];
    state: string;
    pattadarPassbook: [] | [string];
    genericRecordNumber: [] | [string];
    rtcNumber: [] | [string];
    fieldId: bigint;
}): {
    id: bigint;
    pahaniNumber?: string;
    satbaraNumber?: string;
    bhudhaarNumber?: string;
    adangalNumber?: string;
    state: string;
    pattadarPassbook?: string;
    genericRecordNumber?: string;
    rtcNumber?: string;
    fieldId: bigint;
} {
    return {
        id: value.id,
        pahaniNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pahaniNumber)),
        satbaraNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.satbaraNumber)),
        bhudhaarNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bhudhaarNumber)),
        adangalNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.adangalNumber)),
        state: value.state,
        pattadarPassbook: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pattadarPassbook)),
        genericRecordNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.genericRecordNumber)),
        rtcNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.rtcNumber)),
        fieldId: value.fieldId
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    notifType: string;
    body: string;
    createdAt: _Timestamp;
    soundType: string;
    isRead: boolean;
    snoozedUntil: [] | [_Timestamp];
    isDismissed: boolean;
    recipientPrincipal: Principal;
    farmId: bigint;
}): {
    id: bigint;
    title: string;
    notifType: string;
    body: string;
    createdAt: Timestamp;
    soundType: string;
    isRead: boolean;
    snoozedUntil?: Timestamp;
    isDismissed: boolean;
    recipientPrincipal: Principal;
    farmId: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: value.notifType,
        body: value.body,
        createdAt: value.createdAt,
        soundType: value.soundType,
        isRead: value.isRead,
        snoozedUntil: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.snoozedUntil)),
        isDismissed: value.isDismissed,
        recipientPrincipal: value.recipientPrincipal,
        farmId: value.farmId
    };
}
function from_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    moisturePercent: [] | [number];
    actualYieldQt: number;
    recordedBy: Principal;
    notes: [] | [string];
    qualityGrade: _QualityGrade;
    cropSeasonId: bigint;
    harvestDate: _Timestamp;
}): {
    id: bigint;
    moisturePercent?: number;
    actualYieldQt: number;
    recordedBy: Principal;
    notes?: string;
    qualityGrade: QualityGrade;
    cropSeasonId: bigint;
    harvestDate: Timestamp;
} {
    return {
        id: value.id,
        moisturePercent: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.moisturePercent)),
        actualYieldQt: value.actualYieldQt,
        recordedBy: value.recordedBy,
        notes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.notes)),
        qualityGrade: from_candid_QualityGrade_n82(_uploadFile, _downloadFile, value.qualityGrade),
        cropSeasonId: value.cropSeasonId,
        harvestDate: value.harvestDate
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FarmMember;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FarmMember;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_FarmMember_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Member: null;
} | {
    ViewOnly: null;
} | {
    Admin: null;
}): MemberRole {
    return "Member" in value ? MemberRole.Member : "ViewOnly" in value ? MemberRole.ViewOnly : "Admin" in value ? MemberRole.Admin : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Farm;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Farm;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Farm_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ClassificationCode;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ClassificationCode;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CropSeason;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CropSeason;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CropSeason_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Germination: null;
} | {
    GrainFilling: null;
} | {
    Sowing: null;
} | {
    Harvest: null;
} | {
    LandPrep: null;
} | {
    PostHarvest: null;
} | {
    Vegetative: null;
} | {
    Flowering: null;
}): CropStage {
    return "Germination" in value ? CropStage.Germination : "GrainFilling" in value ? CropStage.GrainFilling : "Sowing" in value ? CropStage.Sowing : "Harvest" in value ? CropStage.Harvest : "LandPrep" in value ? CropStage.LandPrep : "PostHarvest" in value ? CropStage.PostHarvest : "Vegetative" in value ? CropStage.Vegetative : "Flowering" in value ? CropStage.Flowering : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Field;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Field;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Field_n33(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _InviteToken;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: InviteToken;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_InviteToken_n39(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_InviteToken>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<InviteToken>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n43(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AuditLog>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AuditLog>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_CropMSP];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CropMSP | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n50(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_CropSeason>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<CropSeason>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n53(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_FarmMember>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<FarmMember>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n56(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FarmerProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FarmerProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_FarmerProfile_n59(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Field>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Field>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n63(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_LandRecord];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LandRecord | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n66(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_NotificationEntity>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<NotificationEntity>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n71(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CropHarvest;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CropHarvest;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CropHarvest_n80(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FAQ: null;
} | {
    GradeA: null;
} | {
    GradeB: null;
} | {
    Rejected: null;
} | {
    Processing: null;
}): QualityGrade {
    return "FAQ" in value ? QualityGrade.FAQ : "GradeA" in value ? QualityGrade.GradeA : "GradeB" in value ? QualityGrade.GradeB : "Rejected" in value ? QualityGrade.Rejected : "Processing" in value ? QualityGrade.Processing : value;
}
function from_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LandRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LandRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LandRecord_n67(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InviteToken>): Array<InviteToken> {
    return value.map((x)=>from_candid_InviteToken_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CropSeason>): Array<CropSeason> {
    return value.map((x)=>from_candid_CropSeason_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FarmMember>): Array<FarmMember> {
    return value.map((x)=>from_candid_FarmMember_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Field>): Array<Field> {
    return value.map((x)=>from_candid_Field_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationEntity>): Array<NotificationEntity> {
    return value.map((x)=>from_candid_NotificationEntity_n72(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Farm>): Array<Farm> {
    return value.map((x)=>from_candid_Farm_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CropStage_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropStage): _CropStage {
    return to_candid_variant_n91(_uploadFile, _downloadFile, value);
}
function to_candid_FarmerProfile_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmerProfile): _FarmerProfile {
    return to_candid_record_n85(_uploadFile, _downloadFile, value);
}
function to_candid_MemberRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberRole): _MemberRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_QualityGrade_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QualityGrade): _QualityGrade {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_SaveLandRecordInput_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveLandRecordInput): _SaveLandRecordInput {
    return to_candid_record_n87(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFarmInput_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFarmInput): _UpdateFarmInput {
    return to_candid_record_n93(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFieldInput_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFieldInput): _UpdateFieldInput {
    return to_candid_record_n95(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fssaiNumber?: string;
    principal: Principal;
    bankLast4?: string;
    gstNumber?: string;
    name: string;
    fpoMember: boolean;
    bankIfsc?: string;
    aadhaarBankLinked: boolean;
    mobile?: string;
    agristackId?: string;
    bankBranch?: string;
}): {
    fssaiNumber: [] | [string];
    principal: Principal;
    bankLast4: [] | [string];
    gstNumber: [] | [string];
    name: string;
    fpoMember: boolean;
    bankIfsc: [] | [string];
    aadhaarBankLinked: boolean;
    mobile: [] | [string];
    agristackId: [] | [string];
    bankBranch: [] | [string];
} {
    return {
        fssaiNumber: value.fssaiNumber ? candid_some(value.fssaiNumber) : candid_none(),
        principal: value.principal,
        bankLast4: value.bankLast4 ? candid_some(value.bankLast4) : candid_none(),
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        fpoMember: value.fpoMember,
        bankIfsc: value.bankIfsc ? candid_some(value.bankIfsc) : candid_none(),
        aadhaarBankLinked: value.aadhaarBankLinked,
        mobile: value.mobile ? candid_some(value.mobile) : candid_none(),
        agristackId: value.agristackId ? candid_some(value.agristackId) : candid_none(),
        bankBranch: value.bankBranch ? candid_some(value.bankBranch) : candid_none()
    };
}
function to_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pahaniNumber?: string;
    satbaraNumber?: string;
    bhudhaarNumber?: string;
    adangalNumber?: string;
    state: string;
    pattadarPassbook?: string;
    genericRecordNumber?: string;
    rtcNumber?: string;
}): {
    pahaniNumber: [] | [string];
    satbaraNumber: [] | [string];
    bhudhaarNumber: [] | [string];
    adangalNumber: [] | [string];
    state: string;
    pattadarPassbook: [] | [string];
    genericRecordNumber: [] | [string];
    rtcNumber: [] | [string];
} {
    return {
        pahaniNumber: value.pahaniNumber ? candid_some(value.pahaniNumber) : candid_none(),
        satbaraNumber: value.satbaraNumber ? candid_some(value.satbaraNumber) : candid_none(),
        bhudhaarNumber: value.bhudhaarNumber ? candid_some(value.bhudhaarNumber) : candid_none(),
        adangalNumber: value.adangalNumber ? candid_some(value.adangalNumber) : candid_none(),
        state: value.state,
        pattadarPassbook: value.pattadarPassbook ? candid_some(value.pattadarPassbook) : candid_none(),
        genericRecordNumber: value.genericRecordNumber ? candid_some(value.genericRecordNumber) : candid_none(),
        rtcNumber: value.rtcNumber ? candid_some(value.rtcNumber) : candid_none()
    };
}
function to_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ownershipType?: string;
    name?: string;
    surveyNumber?: string;
    purposes?: Array<string>;
    totalAreaSqm?: bigint;
    district?: string;
    village?: string;
    mandal?: string;
}): {
    ownershipType: [] | [string];
    name: [] | [string];
    surveyNumber: [] | [string];
    purposes: [] | [Array<string>];
    totalAreaSqm: [] | [bigint];
    district: [] | [string];
    village: [] | [string];
    mandal: [] | [string];
} {
    return {
        ownershipType: value.ownershipType ? candid_some(value.ownershipType) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        surveyNumber: value.surveyNumber ? candid_some(value.surveyNumber) : candid_none(),
        purposes: value.purposes ? candid_some(value.purposes) : candid_none(),
        totalAreaSqm: value.totalAreaSqm ? candid_some(value.totalAreaSqm) : candid_none(),
        district: value.district ? candid_some(value.district) : candid_none(),
        village: value.village ? candid_some(value.village) : candid_none(),
        mandal: value.mandal ? candid_some(value.mandal) : candid_none()
    };
}
function to_candid_record_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shcExpiry?: Timestamp;
    soilType?: string;
    irrigationType?: string;
    name?: string;
    unit?: string;
    surveyNumber?: string;
    geoPoints?: Array<[number, number]>;
    ulpin?: string;
    areaSqm?: bigint;
    tenure?: string;
    shcNumber?: string;
}): {
    shcExpiry: [] | [_Timestamp];
    soilType: [] | [string];
    irrigationType: [] | [string];
    name: [] | [string];
    unit: [] | [string];
    surveyNumber: [] | [string];
    geoPoints: [] | [Array<[number, number]>];
    ulpin: [] | [string];
    areaSqm: [] | [bigint];
    tenure: [] | [string];
    shcNumber: [] | [string];
} {
    return {
        shcExpiry: value.shcExpiry ? candid_some(value.shcExpiry) : candid_none(),
        soilType: value.soilType ? candid_some(value.soilType) : candid_none(),
        irrigationType: value.irrigationType ? candid_some(value.irrigationType) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        unit: value.unit ? candid_some(value.unit) : candid_none(),
        surveyNumber: value.surveyNumber ? candid_some(value.surveyNumber) : candid_none(),
        geoPoints: value.geoPoints ? candid_some(value.geoPoints) : candid_none(),
        ulpin: value.ulpin ? candid_some(value.ulpin) : candid_none(),
        areaSqm: value.areaSqm ? candid_some(value.areaSqm) : candid_none(),
        tenure: value.tenure ? candid_some(value.tenure) : candid_none(),
        shcNumber: value.shcNumber ? candid_some(value.shcNumber) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QualityGrade): {
    FAQ: null;
} | {
    GradeA: null;
} | {
    GradeB: null;
} | {
    Rejected: null;
} | {
    Processing: null;
} {
    return value == QualityGrade.FAQ ? {
        FAQ: null
    } : value == QualityGrade.GradeA ? {
        GradeA: null
    } : value == QualityGrade.GradeB ? {
        GradeB: null
    } : value == QualityGrade.Rejected ? {
        Rejected: null
    } : value == QualityGrade.Processing ? {
        Processing: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberRole): {
    Member: null;
} | {
    ViewOnly: null;
} | {
    Admin: null;
} {
    return value == MemberRole.Member ? {
        Member: null
    } : value == MemberRole.ViewOnly ? {
        ViewOnly: null
    } : value == MemberRole.Admin ? {
        Admin: null
    } : value;
}
function to_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CropStage): {
    Germination: null;
} | {
    GrainFilling: null;
} | {
    Sowing: null;
} | {
    Harvest: null;
} | {
    LandPrep: null;
} | {
    PostHarvest: null;
} | {
    Vegetative: null;
} | {
    Flowering: null;
} {
    return value == CropStage.Germination ? {
        Germination: null
    } : value == CropStage.GrainFilling ? {
        GrainFilling: null
    } : value == CropStage.Sowing ? {
        Sowing: null
    } : value == CropStage.Harvest ? {
        Harvest: null
    } : value == CropStage.LandPrep ? {
        LandPrep: null
    } : value == CropStage.PostHarvest ? {
        PostHarvest: null
    } : value == CropStage.Vegetative ? {
        Vegetative: null
    } : value == CropStage.Flowering ? {
        Flowering: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
